"""Independent arithmetic expectations, not snapshots generated by the builder."""

import copy
import json
from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT), str(ROOT / 'services/ml-service')]
from app.features.service_features import build_features
from jsonschema import Draft202012Validator, FormatChecker, ValidationError


def read(path):
    return json.loads((ROOT / path).read_text(encoding='utf-8'))


def observation(name):
    return read('contracts/fixtures/observations/' + name + '.json')


def context(service='VOLTE'):
    scope = 'VOLTE-MD-CENTRAL' if service == 'VOLTE' else 'SMS-MD-ROUTE-A'
    return dict(baselineVersion='baseline-v2', status='DIRECT', scopeId=scope,
                sourceScopeId=scope, service=service, hourOfWeek=32,
                values=({'cssrPct': 99.3, 'rrcSrPct': 99.5, 'bearerSrPct': 99.0}
                        if service == 'VOLTE' else {'p95DeliveryMs': 2000, 'deliverySrPct': 99.0}))


class FeatureTests(unittest.TestCase):
    def test_shared_raw_expected_cases(self):
        suite = read('contracts/fixtures/features/parity-v2.json')
        validator = Draft202012Validator(read('contracts/features/service-feature-window-v2.schema.json'),
                                        format_checker=FormatChecker())
        for case in suite['cases']:
            with self.subTest(case=case['id']):
                raw = observation(case['observation'])
                raw.update(case.get('envelopePatch', {}))
                if 'metrics' in raw:
                    raw['metrics'].update(case.get('metricsPatch', {}))
                nodes = [observation(name) for name in case['nodes']]
                baseline = context(raw['service'])
                result = build_features(raw, nodes, baseline)
                validator.validate(result)
                if case['id'] == 'voice-worked-53':
                    self.assertEqual(result, read('contracts/fixtures/features/voice-worked-v2.json'))
                expected = case['expected']
                self.assertEqual(result['mlEligible'], expected['mlEligible'])
                self.assertEqual(len(result['featureValues']), len(expected['featureValues']))
                for actual, wanted in zip(result['featureValues'], expected['featureValues']):
                    self.assertEqual(actual, wanted) if isinstance(wanted, int) else self.assertAlmostEqual(actual, wanted, delta=1e-9)
                actual_kpis = {k['name']: k for k in result['kpis']}
                for name, wanted in expected['kpis'].items():
                    actual = actual_kpis[name]['observed']
                    if wanted is None:
                        self.assertIsNone(actual)
                    else:
                        self.assertEqual(actual, wanted) if isinstance(wanted, int) else self.assertAlmostEqual(actual, wanted, delta=1e-9)

    def test_null_denominators_and_incomplete_never_become_healthy_zeros(self):
        raw = observation('normal-volte')
        raw['metrics'] = {key: 0 for key in raw['metrics']}
        result = build_features(raw, [], context())
        self.assertFalse(result['mlEligible'])
        self.assertEqual(result['featureNames'], [])
        self.assertIsNone(next(k['observed'] for k in result['kpis'] if k['name'] == 'cssrPct'))

    def test_nearest_rank_is_not_interpolation(self):
        raw = observation('normal-sms')
        raw['metrics'].update(deliveryAttempts=30, deliverySuccesses=30,
                              deliveredMessages=30, deliveryDelayMs=list(range(30, 0, -1)))
        result = build_features(raw, [observation('normal-smsc')], context('SMS'))
        self.assertEqual(result['featureValues'][1], 29)

    def test_rejects_impossible_counts_wrong_units_and_nonfinite_numbers(self):
        cases = [('normal-volte', 'technicalSuccesses', 2000),
                 ('normal-volte', 'rrcSuccesses', 1201),
                 ('normal-volte', 'sip503Count', 6),
                 ('normal-sms', 'deliveredMessages', 99),
                 ('normal-sms', 'deliveryDelayMs', [float('nan')] * 100),
                 ('normal-sms', 'deliveryDelayMs', [float('inf')] * 100)]
        for name, key, value in cases:
            with self.subTest(key=key, value=str(value)[:20]):
                raw = observation(name)
                raw['metrics'][key] = value
                with self.assertRaises((ValueError, ValidationError)):
                    build_features(raw, [], context(raw['service']))

    def test_missing_nodes_baselines_and_zero_delay_baseline(self):
        raw = observation('normal-volte')
        self.assertFalse(build_features(raw, [], context())['mlEligible'])
        absent = context()
        absent.update(status='BASELINE_MISSING', sourceScopeId=None, values={})
        result = build_features(raw, [observation('normal-ims'), observation('normal-transport')], absent)
        self.assertFalse(result['mlEligible'])
        self.assertEqual(result['kpis'][0]['observed'], 99.5)
        sms = context('SMS')
        sms['values']['p95DeliveryMs'] = 0
        result = build_features(observation('normal-sms'), [observation('normal-smsc')], sms)
        self.assertFalse(result['mlEligible'])
        self.assertEqual(next(k['observed'] for k in result['kpis'] if k['name']=='p95DeliveryMs'), 2000)

    def test_only_aligned_authorized_nodes_contribute(self):
        raw = observation('normal-volte')
        stale = observation('normal-ims')
        stale.update(windowStart='2026-09-15T07:59:00Z', windowEnd='2026-09-15T08:00:00Z')
        nodes = [stale, observation('normal-transport'), observation('normal-smsc')]
        result = build_features(raw, nodes, context())
        self.assertFalse(result['mlEligible'])
        self.assertNotIn(stale['eventId'], result['sourceEventIds'])
        wrong = observation('normal-ims')
        wrong['sourceId'] = 'UNKNOWN'
        with self.assertRaises(ValueError):
            build_features(raw, [wrong], context())

    def test_retry_is_stable_conflict_is_rejected_and_inputs_are_unchanged(self):
        raw, node = observation('normal-volte'), observation('normal-ims')
        before = copy.deepcopy(raw)
        once = build_features(raw, [node], context())
        self.assertEqual(once, build_features(raw, [node, copy.deepcopy(node)], context()))
        self.assertEqual(raw, before)
        conflict = copy.deepcopy(node)
        conflict['metrics']['cpuPct'] = 70
        with self.assertRaises(ValueError):
            build_features(raw, [node, conflict], context())

    def test_valid_large_measurement_keeps_kpis_but_skips_model_vector(self):
        raw = observation('normal-sms')
        raw['metrics']['deliveryDelayMs'] = [1000000001] * 100
        result = build_features(raw, [observation('normal-smsc')], context('SMS'))
        self.assertFalse(result['mlEligible'])
        self.assertEqual(result['featureValues'], [])
        self.assertEqual(next(k['observed'] for k in result['kpis'] if k['name'] == 'p95DeliveryMs'), 1000000001)

    def test_wrong_baseline_context_is_rejected(self):
        for field, value in [('scopeId', 'OTHER'), ('service', 'SMS'), ('hourOfWeek', 33)]:
            baseline = context()
            baseline[field] = value
            with self.assertRaises(ValueError):
                build_features(observation('normal-volte'), [], baseline)


if __name__ == '__main__':
    unittest.main()
