<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.16</version>
    <relativePath/>
  </parent>
  <groupId>md.utm.telecom</groupId>
  <artifactId>telecom-anomaly-detection</artifactId>
  <version>0.3.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <properties>
    <java.version>21</java.version>
    <json-schema-validator.version>1.5.9</json-schema-validator.version>
  </properties>
  <modules>
    <module>services/streaming-support</module>
    <module>services/event-generator</module>
    <module>services/processor</module>
  </modules>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>md.utm.telecom</groupId>
        <artifactId>streaming-support</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.networknt</groupId>
        <artifactId>json-schema-validator</artifactId>
        <version>${json-schema-validator.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
