#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PROCESSING_DB_USER}') THEN
    CREATE ROLE ${PROCESSING_DB_USER} LOGIN PASSWORD '${PROCESSING_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${INCIDENT_DB_USER}') THEN
    CREATE ROLE ${INCIDENT_DB_USER} LOGIN PASSWORD '${INCIDENT_DB_PASSWORD}';
  END IF;
END
\$\$;

CREATE SCHEMA IF NOT EXISTS processing AUTHORIZATION ${PROCESSING_DB_USER};
CREATE SCHEMA IF NOT EXISTS incidents AUTHORIZATION ${INCIDENT_DB_USER};

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${PROCESSING_DB_USER}, ${INCIDENT_DB_USER};
GRANT USAGE, CREATE ON SCHEMA processing TO ${PROCESSING_DB_USER};
GRANT USAGE, CREATE ON SCHEMA incidents TO ${INCIDENT_DB_USER};
EOSQL
